# COPYRIGHT Dassault Systemes 2018
#======================================================================
# Imakefile for module AssemblePart.m
#======================================================================
#
#  Apr 2018  Creation: Code generated by the CAA wizard  CAD-X
#======================================================================
#
# SHARED LIBRARY 
#
BUILT_OBJECT_TYPE=SHARED LIBRARY 
 
# DO NOT EDIT :: THE CAA2 WIZARDS WILL ADD CODE HERE
WIZARD_LINK_MODULES = JS0GROUP \
JS0FM JS0GROUP ApplicationFrame CATAfrUUID \
CATApplicationFrame  \
CATIAApplicationFrame  \ \
DI0PANV2 
# END WIZARD EDITION ZONE

LINK_WITH = $(WIZARD_LINK_MODULES)

# System dependant variables
#
OS = AIX
#
OS = HP-UX
#
OS = IRIX
#
OS = SunOS
#
OS = Windows_NT
