// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// CAAEPartSubMenu.cpp
// Provide implementation to interface
//    CATIContextualSubMenu
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//  Apr 2018  Creation: Code generated by the CAA wizard  CAD-X
//===================================================================
#include "CAAEPartSubMenu.h"
#include "CATCreateWorkshop.h"

#include "CATCmdStarter.h"

#include <iostream.h>
CATImplementClass(CAAEPartSubMenu,
                  DataExtension,
                  CATBaseUnknown,
                  MechanicalPart);



//-----------------------------------------------------------------------------
// CAAEPartSubMenu : constructor
//-----------------------------------------------------------------------------
CAAEPartSubMenu::CAAEPartSubMenu():
    CATBaseUnknown()
{
	NewAccess(CATCmdStarter,pCAAMmrParentChildrenStr,CAAMmrParentChildrenStr);
	SetAccessCommand(pCAAMmrParentChildrenStr,"CATMmuReorderChildrenHdr");

	NewAccess(CATCmdStarter,pCAAMmrResetPropertiesStr,CAAMmrResetPropertiesStr);
	SetAccessCommand(pCAAMmrResetPropertiesStr,"CATMmrUpdateAllLinkHdr");
    SetAccessNext(pCAAMmrParentChildrenStr,pCAAMmrResetPropertiesStr);

	NewAccess(CATCmdStarter,pCAAAssemble,CAAAssembleStr);
	SetAccessNext(pCAAMmrResetPropertiesStr,pCAAAssemble);
	SetAccessCommand(pCAAAssemble,"CAAAfrMRUHdr");

	
	
	//SetAccessAnchorName(pCAARenameBool,"CATMmrUpdateAllLinkHdr");

	//SetAccessCommand(pCAAMmrParentChildrenStr,"CATParentChildrenHdr");
	_pMenu = pCAAMmrParentChildrenStr;
	//_pMenu = pCAAMmrParentChildrenStr ;
	cout<<"Menu Activitied!"<<endl;
}

//-----------------------------------------------------------------------------
// CAAEPartSubMenu : destructor
//-----------------------------------------------------------------------------
CAAEPartSubMenu::~CAAEPartSubMenu()
{
}
 
// Link the implementation to its interface
// ---------------------------------------
//TIE or TIEchain definitions
#include "TIE_CATIContextualSubMenu.h"
TIE_CATIContextualSubMenu(CAAEPartSubMenu);




//Methods implementation

//-----------------------------------------------------------------------------
// Implements CATIContextualSubMenu::GetContextualSubMenu
//-----------------------------------------------------------------------------
CATCmdAccess * CAAEPartSubMenu::GetContextualSubMenu ()
{

   

   return (CATCmdAccess *)_pMenu;
}

