// COPYRIGHT Dassault Systemes 2018
//===================================================================
//
// CAAEPartSubMenu.h
// Provide implementation to interface
//    CATIContextualSubMenu

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	MechanicalPart
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIContextualSubMenu

//End CAA2 Wizard Generation Report
//
//  Apr 2018  Creation: Code generated by the CAA wizard  CAD-X
//===================================================================
#ifndef CAAEPartSubMenu_H
#define CAAEPartSubMenu_H

#include "CATBaseUnknown.h"
#include "CATCmdAccess.h"
#include "CATExtIContextualMenu.h"
#include "CATCmdContainer.h"
//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIContextualSubMenu
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class CAAEPartSubMenu: public CATBaseUnknown

{
  CATDeclareClass;

  public:

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     CAAEPartSubMenu ();
     virtual ~CAAEPartSubMenu ();

    /**
     * Implements a function from an interface.
     * @href CATIContextualSubMenu#GetContextualSubMenu
     */
     CATCmdAccess * GetContextualSubMenu () ;


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  CAAEPartSubMenu (CAAEPartSubMenu &);
  CAAEPartSubMenu& operator=(CAAEPartSubMenu&);
  CATCmdAccess *  _pMenu ;
};

//-----------------------------------------------------------------------

#endif
